### ISSUE TITLE
Ознакомиться с документацией проекта

### ISSUE THREAD

**Issue by dmitrii-nikiforov** [yp-team-rn3dt/react-project-kitchen-frontend#1]
[воркспейс](https://concrete-web-bad.notion.site/15-1-911766e6785e4b97bd2fa8b5d21c2dc2)

Оставьте любой комментарий, если ознакомились с документацией предоставленной в воркспейсе

**Comment by JustKing** [comment]
- [ ] Сергей Кисляк
- [ ] Александр Кузнецов
- [ ] Иван Семенов
- [ ] Булат Мустафин
- [ ] Ярослав Королев
- [ ] Дмитрий Никифоров
- [ ] Александр Сергеев
- [ ] Александра Гусева

**Comment by dmitrii-nikiforov** [comment]
\+

**Comment by bospur** [comment]
+

**Comment by Surtt** [comment]
+

**Comment by kislak** [comment]
+

**Comment by guseva-47** [comment]
+

**Comment by AlexTolevich** [comment]
+

**Comment by bulat92** [comment]
+
