### ISSUE TITLE
Запустить проект

### ISSUE THREAD

**Issue by dmitrii-nikiforov** [yp-team-rn3dt/react-project-kitchen-frontend#4]
1. Бекенд можно запустить у себя через докер, воспользовавшись командой `docker compose up --build -d`
2. Отметьте любой комментарий, если запустили проект и потыкались в нем

**Comment by JustKing** [comment]
- [ ] Сергей Кисляк
- [ ] Александр Кузнецов
- [ ] Иван Семенов
- [ ] Булат Мустафин
- [ ] Ярослав Королев
- [ ] Дмитрий Никифоров
- [ ] Александр Сергеев
- [ ] Александра Гусева

**Comment by dmitrii-nikiforov** [comment]
\+

**Comment by kislak** [comment]
+

**Comment by guseva-47** [comment]
+

**Comment by Surtt** [comment]
+

**Comment by bospur** [comment]
+

**Comment by bulat92** [comment]
+
