### ISSUE TITLE
Установить редактор исходного кода

### ISSUE THREAD

**Issue by dmitrii-nikiforov** [yp-team-rn3dt/react-project-kitchen-frontend#5]
Установите удобный для Вас vscode, web storm, atom etc..

Рекомендую `vscode` и расширения к нему:
1. GitLens - упрощает работу с гитом, позволяет быстро проводить ревизию изменений и показывает построчно инфу - кто менял, когда и какой коммит и т.д.;
2. Prettier - code formatter - форматирование кода - чтобы все в команде писали в одном стиле;
3. GitGraph - визуализирует работу с гитом;
4. EsLint - соответственно линтер.

Отметьте любой комментарий, если установили

**Comment by JustKing** [comment]
+

**Comment by dmitrii-nikiforov** [comment]
\+

**Comment by bospur** [comment]
+

**Comment by bulat92** [comment]
+

**Comment by bulat92** [comment]
+

**Comment by Surtt** [comment]
+

**Comment by kislak** [comment]
+

**Comment by guseva-47** [comment]
+

**Comment by bulat92** [comment]
+
